[package]
name = "neko-crypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
argon2.workspace = true
chacha20poly1305.workspace = true
hkdf.workspace = true
sha2.workspace = true
hmac.workspace = true
subtle.workspace = true
zeroize.workspace = true
getrandom.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
