//! Cryptographic primitives for neko-wallet.
//!
//! Pure functions only: no I/O, no SQL, no async. Everything here is covered by
//! the frozen cross-language vectors in `vectors/crypto.json`, which were
//! generated by the Go implementation and independently reproduced in
//! TypeScript. Any divergence means ciphertext this build cannot read.

pub mod aad;
pub mod aead;
pub mod error;
pub mod kdf;
pub mod kdf_hkdf;

pub use aad::Aad;
pub use aead::{open, seal, KEY_LEN, NONCE_LEN, TAG_LEN};
pub use error::CryptoError;
pub use kdf::{derive_key, Argon2idParams};
pub use kdf_hkdf::{derive, derive_from_ikm, derive_key32, derive_with_salt, hmac_sha256, info};

use zeroize::Zeroizing;

/// Fill a fresh buffer with cryptographically secure random bytes.
pub fn random(len: usize) -> Result<Zeroizing<Vec<u8>>, CryptoError> {
    let mut out = Zeroizing::new(vec![0u8; len]);
    getrandom::getrandom(&mut out).map_err(|_| CryptoError::NoEntropy)?;
    Ok(out)
}

/// Constant-time equality. Never compare secrets with `==`.
pub fn ct_eq(a: &[u8], b: &[u8]) -> bool {
    use subtle::ConstantTimeEq;
    a.len() == b.len() && bool::from(a.ct_eq(b))
}
