[package]
name = "neko-hd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
bip32.workspace = true
bip39.workspace = true
k256.workspace = true
sha2.workspace = true
sha3.workspace = true
bs58.workspace = true
ed25519-dalek.workspace = true
hmac.workspace = true
zeroize.workspace = true
thiserror.workspace = true

[dev-dependencies]
bip32.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
